# WDPA Metadata
## _Last updated: 9 Oct 2018_
___

### Title
World Database on Protected Areas  

### Description
The World Database on Protected Areas (WDPA) is a joint project between UN Environment and the International Union for Conservation of Nature (IUCN). It is compiled and managed by the UN Environment World Conservation Monitoring Centre (UNEP-WCMC), in collaboration with governments, non-governmental organisations, academia and industry. The WDPA is the most comprehensive global database of marine and terrestrial protected areas, comprising both spatial data (i.e. boundaries and points) with associated attribute data (i.e. tabular information). It is made available online through Protected Planet (www.protectedplanet.net) where the data is both viewable and downloadable. 
Manual: https://www.protectedplanet.net/c/wdpa-manual/wdpa-manual-v15  

### Date Accessed  
August 2018 from www.protectedplant.net

### Publisher  
United Nations Environment World Conservation Monitoring Centre (UNEP-WCMC) 

### File Format  
Shapefile - data provided as spatial polygons representing site boundaries and points where polygon data are not available.      

### Access URL  
UNEP-WCMC and IUCN (2018), Protected Planet: The World Database on Protected Areas (WDPA)[On-line], Downloaded Aug 2018, Cambridge, UK: UNEP-WCMC and IUCN. Available at: www.protectedplanet.net. 

### Temporal Range & Frequency
The year associated with each site in the WDPA corresponds to the year it was given its' designation. The earliest sites were established before 1900, however some sites do not have a year associated with their designation. The dataset extends to the current year (2018), and is updated on a monthly basis. In this analysis, sites where the year is unknown (STATUS_YR = 0 in dataset) were aggregated with years 1995 and prior.   

### Spatial Range & Resolution
Global extent. Resolution is variable among sites as a result of different managing/reporting entities. While some sites may provide highly detailed shapefile boundaries, other sites may only report an area and not have GIS capablities. 

### Contact Name and Email (of Publisher)
protectedareas@unep-wcmc.org  

### Contact Name and Email (within WWF)
Colleen Nell (collnellphd@gmail.com)

### Data Permissions (License & Rights)

Source: https://www.protectedplanet.net/c/terms-and-conditions  
Neither (a) the WDPA Materials nor (b) any work derived from or based upon the WDPA Materials (“Derivative Works") may be put to Commercial Use without the prior written permission of UNEP-WCMC. For the purposes of these Terms and Conditions, “Commercial Use" means a) any use by, on behalf of, or to inform or assist the activities of, a commercial entity (an entity that operates 'for profit') or b) use by any individual or non-profit entity for the purposes of revenue generation To apply for permission for Commercial Use of the WDPA Materials please send an email to business-support@unep-wcmc.org outlining your needs.

The WDPA Materials may not be sub-licensed in whole or in part including within Derivative Works without the prior written permission of UNEP-WCMC. You may not redistribute the WDPA Data contained in the WDPA in whole or in part by any means including (but not limited to) electronic formats such as web downloads, through web services, through interactive web maps (including mobile applications) that grant users download access, KML Files or through file transfer protocols. If you know of others who wish to use the WDPA Data please refer them to protectedplanet.net. If you wish to provide a service through which the WDPA Data are downloadable or otherwise made available for redistribution you must contact protectedareas@unep-wcmc.org for permission and further guidance.  

###  Statistical Processing  

**Calculate global protected area coverage (total cover, marine, terrestrial, & within ABNJ)**    

Steps follow WCMC-UNEP: https://www.protectedplanet.net/c/calculating-protected-area-coverage 
R script: WDPA_calculate_PA.R  

1. Using the monthly release from August 2018, data were filtered to sites with a status of either 'designated', 'inscribed', or 'established' following IUCN definition of a protected area (http://www.biodiversitya-z.org/content/protected-area). UNESCO Man and Biosphere Reserves are excluded by this definition.
2. For point data, sites with no reported area were excluded. For remaining sites, reported area was used to calculate the radius of a circle with the given area and used to buffer spatial points into polygons. Buffered points and polygons were then combined and spatially aggregated by year for each unique ISO3 code. Due to multiple designations and misreporting of areas, protected areas can frequently overlap in the WDPA. This spatial union accounts for this and prevents double-counting of areas under the same ISO3.  
3. Protected areas were then intersected with global boundaries for Exclusive Economic Zones (EEZ) and terrestrial borders to delineate as marine (within EEZ) or terrestrial.  Geometries were repaired as necessary. Areas beyond national jurisdiction (ABNJ) were not included. The basemap layer used was provided by Brooks et al.2016 (https://doi.org/10.5061/dryad.6gb90.2).   
4. For each year from 1995 - present, the intersected files were aggregated by geographic subregions for marine and terrestrial separately. For year 1995, all years before 1996 were aggregated together. In some cases, the year of designation for a site is unknown or not reported and treated as year 0 in these analyses. Transboundary sites that were assigned multiple ISO3 codes were split and aggregated based upon subregional boundaries. Global figures reflect the composite value of each geographic subregion. Again, this aggregation at the subregional level creates a union between overlapping spatial polygons to account for sites with multiple designations.   
5. The global extent of protected area was calculated in M ha as the total coverage in each subregion for terrestrial and marine sites. These data were also used to calculate protected area coverage separately for terrestrial and marine. Mollweide projection was used for area calculations. 

**Calculate ICCA coverage**  
R script: WDPA_calculate_ICCA.R  

1. Using the monthly release from August 2018, data were filtered to sites designated as ICCAs by selecting sites in which the 'GOV_TYPE' was either "Local communities" or "Indigenous peoples".  
2. For point data, sites with no reported area were excluded. For remaining sites, reported area was used to calculate the radius of a circle with the given area and used to buffer spatial points into polygons. Buffered points and polygons were then combined and spatially aggregated by year for each unique ISO3 code. Due to multiple designations and misreporting of areas, protected areas can frequently overlap in the WDPA. This spatial union accounts for this and prevents double-counting of areas under the same ISO3.  


